# Generated by Django 5.0.2 on 2024-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='body3',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='body4',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='body5',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='subhead2',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='subhead3',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='subhead4',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='subhead5',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
