# Generated by Django 5.0.2 on 2024-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body2_post_body3_post_body4_post_body5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subhead5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
