# Generated by Django 5.0.2 on 2024-03-04 00:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image_alter_post_image2_alter_post_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subhead',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subhead2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subhead3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subhead4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subhead5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
