# Generated by Django 5.0.3 on 2024-09-19 20:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bullets',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
