# Generated by Django 5.0.3 on 2024-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_company_post_link_post_role_post_surface_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
