# Generated by Django 5.0.3 on 2024-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_bullets_remove_post_thumbnail_post_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
