# Generated by Django 5.0.3 on 2025-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_brand_post_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='body',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
