# Generated by Django 5.0.3 on 2025-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_brand_body_brand_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
