# Generated by Django 5.0.3 on 2025-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_brand_link_post_image2_post_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
