# Generated by Django 5.0.3 on 2025-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_brand_link_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
