# Generated by Django 5.0.3 on 2025-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
        migrations.RemoveField(
            model_name='post',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='position',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
