# Generated by Django 5.0.3 on 2025-12-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=0, help_text='Order in which media appears')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['position', 'created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
